scripts: >&2 -> 1>&2

diff --git a/docker/cs16-server-lan/manage-container b/docker/cs16-server-lan/manage-container
--- a/docker/cs16-server-lan/manage-container
+++ b/docker/cs16-server-lan/manage-container
@@ -3,11 +3,11 @@
 set -euo pipefail
 
 print_help() {
-    printf "Usage: %s <build | deploy | start | restart | stop>\n" "$(basename "${0}")"
+    printf "Usage: %s <build | deploy | start | restart | stop>\n" "${0##*/}"
 }
 
 if [[ "${#}" -gt 1 ]]; then
-    printf "Only 1 command is accepted\n" >&2
+    printf "Only 1 command is accepted\n" 1>&2
     print_help
     exit 1
 elif [[ "${#}" -eq 0 ]]; then
@@ -32,7 +32,7 @@ case "${1:-}" in
         docker stop cs16-server-lan
         ;;
     *)
-        printf "Invalid command: %s\n" "${1}" >&2
+        printf "Invalid command: %s\n" "${1}" 1>&2
         print_help
         exit 1
         ;;
diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -12,7 +12,7 @@ print_help()
 
 if [ $# -gt 1 ]
 then
-    printf "%s: only 1 option is accepted\n" "$progname" >&2
+    printf "%s: only 1 option is accepted\n" "$progname" 1>&2
     print_help
     exit 1
 elif [ $# -eq 0 ]
@@ -29,7 +29,7 @@ case $1 in
         workstation=1
         ;;
     *)
-        printf "%s: invalid option %s\n" "$progname" "$1" >&2
+        printf "%s: invalid option %s\n" "$progname" "$1" 1>&2
         print_help
         exit 1
         ;;
@@ -46,7 +46,7 @@ done
 
 if [ -n "$missing_pkgs" ]
 then
-    printf "install missing packages:%s\n" "$missing_pkgs" >&2
+    printf "install missing packages:%s\n" "$missing_pkgs" 1>&2
     exit 1
 fi
 
diff --git a/scripts/crypt-gpg b/scripts/crypt-gpg
--- a/scripts/crypt-gpg
+++ b/scripts/crypt-gpg
@@ -13,7 +13,7 @@ print_help()
 
 if [ $# -gt 2 ]
 then
-    printf "%s: only 1 option and 1 argument are accepted\n" "$progname" >&2
+    printf "%s: only 1 option and 1 argument are accepted\n" "$progname" 1>&2
     print_help
     exit 1
 elif [ $# -eq 0 ]
@@ -35,7 +35,7 @@ case $1 in
         mode=dec
         ;;
     *)
-        printf "%s: invalid option: %s\n" "$progname" "$1" >&2
+        printf "%s: invalid option: %s\n" "$progname" "$1" 1>&2
         print_help
         exit 1
         ;;
@@ -45,7 +45,7 @@ file=$2
 
 if [ -z "$file" ]
 then
-    printf "%s: %s: missing file argument\n" "$progname" "$1" >&2
+    printf "%s: %s: missing file argument\n" "$progname" "$1" 1>&2
     print_help
     exit 1
 fi
@@ -57,13 +57,13 @@ case $mode in
 
         if [ ! -f "$file_dec" ]
         then
-            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_dec" >&2
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_dec" 1>&2
             exit 1
         fi
 
         if [ -f "$file_enc" ]
         then
-            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_enc" >&2
+            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_enc" 1>&2
             exit 1
         fi
         ;;
@@ -71,7 +71,7 @@ case $mode in
         case $file in
             *.gpg) ;;
             *)
-                printf "%s: %s: not a .gpg file: %s\n" "$progname" "$1" "$file" >&2
+                printf "%s: %s: not a .gpg file: %s\n" "$progname" "$1" "$file" 1>&2
                 exit 1
                 ;;
         esac
@@ -81,13 +81,13 @@ case $mode in
 
         if [ ! -f "$file_enc" ]
         then
-            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_enc" >&2
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_enc" 1>&2
             exit 1
         fi
 
         if [ -f "$file_dec" ]
         then
-            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_dec" >&2
+            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_dec" 1>&2
             exit 1
         fi
         ;;
diff --git a/scripts/crypt-openssl b/scripts/crypt-openssl
--- a/scripts/crypt-openssl
+++ b/scripts/crypt-openssl
@@ -12,7 +12,7 @@ print_help()
 
 if [ $# -gt 2 ]
 then
-    printf "%s: only 1 option and 1 argument are accepted\n" "$progname" >&2
+    printf "%s: only 1 option and 1 argument are accepted\n" "$progname" 1>&2
     print_help
     exit 1
 elif [ $# -eq 0 ]
@@ -31,7 +31,7 @@ case $1 in
         mode=dec
         ;;
     *)
-        printf "%s: invalid option: %s\n" "$progname" "$1" >&2
+        printf "%s: invalid option: %s\n" "$progname" "$1" 1>&2
         print_help
         exit 1
         ;;
@@ -41,7 +41,7 @@ file=$2
 
 if [ -z "$file" ]
 then
-    printf "%s: %s: missing file argument\n" "$progname" "$1" >&2
+    printf "%s: %s: missing file argument\n" "$progname" "$1" 1>&2
     print_help
     exit 1
 fi
@@ -53,13 +53,13 @@ case $mode in
 
         if [ ! -f "$file_dec" ]
         then
-            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_dec" >&2
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_dec" 1>&2
             exit 1
         fi
 
         if [ -f "$file_enc" ]
         then
-            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_enc" >&2
+            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_enc" 1>&2
             exit 1
         fi
         ;;
@@ -67,7 +67,7 @@ case $mode in
         case $file in
             *.enc) ;;
             *)
-                printf "%s: %s: not a .enc file: %s\n" "$progname" "$1" "$file" >&2
+                printf "%s: %s: not a .enc file: %s\n" "$progname" "$1" "$file" 1>&2
                 exit 1
                 ;;
         esac
@@ -77,13 +77,13 @@ case $mode in
 
         if [ ! -f "$file_enc" ]
         then
-            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_enc" >&2
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_enc" 1>&2
             exit 1
         fi
 
         if [ -f "$file_dec" ]
         then
-            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_dec" >&2
+            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_dec" 1>&2
             exit 1
         fi
         ;;
diff --git a/scripts/rename-files-to-random-name b/scripts/rename-files-to-random-name
--- a/scripts/rename-files-to-random-name
+++ b/scripts/rename-files-to-random-name
@@ -6,7 +6,7 @@ progname=${0##*/}
 
 if [ $# -gt 1 ]
 then
-    printf "%s: only 1 argument is accepted\n" "$progname" >&2
+    printf "%s: only 1 argument is accepted\n" "$progname" 1>&2
     print_help
     exit 1
 elif [ $# -eq 0 ]
@@ -25,7 +25,7 @@ case $os_name in
         sha_cmd=sha256sum
         ;;
     *)
-        printf "%s: unable to detect OS for \$sha_cmd\n" "$progname" >&2
+        printf "%s: unable to detect OS for \$sha_cmd\n" "$progname" 1>&2
         exit 1
         ;;
 esac
