docker: update cs16-server manage-container scripts

diff --git a/docker/cs16-server-lan/manage-container b/docker/cs16-server-lan/manage-container
--- a/docker/cs16-server-lan/manage-container
+++ b/docker/cs16-server-lan/manage-container
@@ -2,7 +2,19 @@
 
 set -euo pipefail
 
-cd "$(dirname "${0}")"
+print_help()
+{
+    printf "Usage: %s <build | deploy | start | restart | stop>\n" "$(basename "${0}")"
+}
+
+if [[ "${#}" -gt 1 ]]; then
+    printf "Only one command is accepted\n" >&2
+    print_help
+    exit 1
+elif [[ "${#}" -eq 0 ]]; then
+    print_help
+    exit 0
+fi
 
 case "${1:-}" in
     "build")
@@ -21,7 +33,8 @@ case "${1:-}" in
         docker stop cs16-server-lan
         ;;
     *)
-        printf "Usage: %s <build | deploy | start | restart | stop>\n" "$(basename "${0}")"
+        printf "Invalid command: %s\n" "${1}" >&2
+        print_help
         exit 1
         ;;
 esac
