gpg-file: update

diff --git a/extra/scripts/gpg-file b/extra/scripts/gpg-file
--- a/extra/scripts/gpg-file
+++ b/extra/scripts/gpg-file
@@ -2,13 +2,37 @@
 
 set -e
 
-if [ -z "$1" ] || [ -z "$2" ]; then
+if [ $# -ne 2 ]; then
     printf "Usage: %s <enc | dec> <file>\n" "$(basename "$0")"
     exit 1
 fi
 
 case $1 in
-    enc) gpg -o "$(pwd)"/"$(basename "$2")".gpg --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 -cs "$2" ;;
-    dec) gpg -do "$(pwd)"/"$(basename "$2" .gpg)" "$2" ;;
-    *) exit 1 ;;
+    enc|dec)
+        if [ ! -f "$2" ]; then
+            printf "File %s doesn't exist\n" "$2"
+            exit 1
+        fi
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$1"
+        exit 1
+        ;;
+esac
+
+case $1 in
+    enc)
+        if [ -f "$(basename "$2")".gpg ]; then
+            printf "File %s already exists\n" "$(basename "$2")".gpg
+            exit 1
+        fi
+        gpg -o "$(basename "$2")".gpg --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 -cs "$2"
+        ;;
+    dec)
+        if [ -f "$(basename "$2" .gpg)" ]; then
+            printf "File %s already exists\n" "$(basename "$2" .gpg)"
+            exit 1
+        fi
+        gpg -do "$(basename "$2" .gpg)" "$2"
+        ;;
 esac
