Update

diff --git a/linux/scripts/tty-colorscheme b/linux/scripts/tty-colorscheme
--- a/linux/scripts/tty-colorscheme
+++ b/linux/scripts/tty-colorscheme
@@ -1,21 +1,21 @@
 #!/bin/bash
 
-colorschemes_dir="/etc/tty-colorscheme/colorschemes"
+cs_dir="/etc/tty-colorscheme/colorschemes"
 
-print_help() {
+cs_help() {
     printf "Usage: %s [-lps | colorscheme]\n" "$(basename "$0")"
     printf "  -l    list colorschemes\n"
     printf "  -p    print current palette\n"
-    printf "  -s    shift through colorschemes\n"
+    printf "  -s    shift through colorschemes and fonts\n"
 }
 
-list_colorschemes() {
-    for scheme_file in "${colorschemes_dir}"/*; do
-        basename "${scheme_file}"
+cs_list() {
+    for cs_name in "${cs_dir}"/*; do
+        basename "${cs_name}"
     done
 }
 
-print_current_palette() {
+cs_palette() {
     cnt=0
     for bkgrnd in {40..47}; do
         printf "\e[%sm" "${bkgrnd}"
@@ -30,31 +30,37 @@ print_current_palette() {
     done
 }
 
-shift_colorschemes() {
-    mapfile -t colorschemes_list < <(list_colorschemes)
-    max_ind_schemes="$((${#colorschemes_list[@]}-1))"
-    ind_schemes=-1
+cs_shift() {
+    mapfile -t cs_arr < <(cs_list)
+    max_ind_cs="$((${#cs_arr[@]}-1))"
+    ind_cs=-1
 
-    mapfile -t fonts_list < <(ls /usr/share/kbd/consolefonts/*.psf*)
-    max_ind_fonts="$((${#fonts_list[@]}-1))"
-    ind_fonts=-1
+    get_fonts() {
+        find /usr/share/kbd/consolefonts/*.psf* -exec file {} + \
+            | grep -E 'PC Screen Font | gzip' \
+            | cut -d: -f 1
+    }
+
+    mapfile -t fnt_arr < <(get_fonts)
+    max_ind_fnt="$((${#fnt_arr[@]}-1))"
+    ind_fnt=-1
 
     while true; do
-        if [[ "${ind_fonts}" -gt -1 ]]; then
-            font="${fonts_list[${ind_fonts}]}"
-            setfont "${font}" > /dev/null 2>&1
+        if [[ "${ind_fnt}" -gt -1 ]]; then
+            fnt="${fnt_arr[${ind_fnt}]}"
+            setfont "${fnt}" > /dev/null 2>&1
         fi
 
-        if [[ "${ind_schemes}" -gt -1 ]]; then
-            colorscheme="${colorschemes_list[${ind_schemes}]}"
-            $(basename "$0") "${colorscheme}"
+        if [[ "${ind_cs}" -gt -1 ]]; then
+            cs="${cs_arr[${ind_cs}]}"
+            $(basename "$0") "${cs}"
         else
             clear
-            print_current_palette
+            cs_palette
         fi
 
-        if [[ "${ind_fonts}" -gt -1 ]]; then
-            printf "Setting %s font\n" "$(basename "${font}")"
+        if [[ "${ind_fnt}" -gt -1 ]]; then
+            printf "Setting %s font\n" "$(basename "${fnt}")"
         fi
 
         printf "\nUse j and k keys to shift through colorschemes\n"
@@ -62,20 +68,21 @@ shift_colorschemes() {
 
         read -rsn1
         case "${REPLY}" in
-            j) [[ "${ind_schemes}" -lt "${max_ind_schemes}" ]] && ((ind_schemes++)) ;;
-            k) [[ "${ind_schemes}" -gt 0 ]] && ((ind_schemes--)) ;;
-            l) [[ "${ind_fonts}" -lt "${max_ind_fonts}" ]] && ((ind_fonts++)) ;;
-            h) [[ "${ind_fonts}" -gt 0 ]] && ((ind_fonts--)) ;;
+            j) [[ "${ind_cs}" -lt "${max_ind_cs}" ]] && ((ind_cs++)) ;;
+            k) [[ "${ind_cs}" -gt 0 ]] && ((ind_cs--)) ;;
+            l) [[ "${ind_fnt}" -lt "${max_ind_fnt}" ]] && ((ind_fnt++)) ;;
+            h) [[ "${ind_fnt}" -gt 0 ]] && ((ind_fnt--)) ;;
             *) exit 0 ;;
         esac
     done
 }
 
-set_colorscheme() {
-    colorscheme_file="${colorschemes_dir}/$1"
-    [[ ! -f "${colorscheme_file}" ]] && printf "Invalid colorscheme: %s\n" "$1" && exit 1
-    source "${colorscheme_file}"
-    set_tty_colors() {
+cs_set() {
+    cs_file="${cs_dir}/$1"
+    [[ ! -f "${cs_file}" ]] && printf "Invalid colorscheme: %s\n" "$1" && exit 1
+    source "${cs_file}"
+
+    set_colors() {
         printf "\e]P0%s" "${color01:?}" # Black (Background)
         printf "\e]P1%s" "${color02:?}" # Red
         printf "\e]P2%s" "${color03:?}" # Green
@@ -93,9 +100,11 @@ set_colorscheme() {
         printf "\e]PE%s" "${color15:?}" # Cyan
         printf "\e]PF%s" "${color16:?}" # White
     }
+
     for i in {1..6}; do
-        set_tty_colors > "/dev/tty${i}"
+        set_colors > "/dev/tty${i}"
     done > /dev/null 2>&1
+
     [[ "${TERM}" == "linux" ]] && clear && $(basename "$0") -p
     printf "Setting %s colorscheme\n" "$1"
 }
@@ -103,25 +112,25 @@ set_colorscheme() {
 while getopts ":lps" opt; do
     case "${opt}" in
         l)
-            list_colorschemes
+            cs_list
             exit 0
             ;;
         p)
-            print_current_palette
+            cs_palette
             exit 0
             ;;
         s)
-            shift_colorschemes
+            cs_shift
             exit 0
             ;;
         *)
             printf "Invalid option -%s\n" "${OPTARG}"
-            print_help
+            cs_help
             exit 1
             ;;
     esac
 done
 
-[[ "$#" -eq 1 ]] && set_colorscheme "$1" && exit 0
+[[ "$#" -eq 1 ]] && cs_set "$1" && exit 0
 
-print_help
+cs_help
