Old versions of curl don't have --output-dir

diff --git a/linux/scripts/cs16-server/install b/linux/scripts/cs16-server/install
--- a/linux/scripts/cs16-server/install
+++ b/linux/scripts/cs16-server/install
@@ -42,8 +42,6 @@ if [ -n "$to_install" ]; then
 	exit 1
 fi
 
-mkdir -vm 755 /tmp/cs16-server
-
 set -- \
 https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz \
 https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz \
@@ -51,12 +49,19 @@ https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz \
 https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz \
 https://github.com/APGRoboCop/podbot_mm/releases/download/V3B24-APG/podbot_full_V3B24.zip
 
+work_dir=$(pwd)
+
+mkdir -vm 755 /tmp/cs16-server
+cd /tmp/cs16-server || exit
+
 for link in "$@"; do
 	printf "==> Downloading %s\n" "$link"
-	curl -fLO "$link" --output-dir /tmp/cs16-server && continue
-	printf "Failed downloading %s\n" "$link"
+	curl -fLO "$link" && continue
+	printf "Failed to download %s\n" "$link"
 	exit 1
 done
+
+cd "$work_dir" || exit
 
 chmod -v 644 /tmp/c16-server/*
 
@@ -64,7 +69,7 @@ server_user=steam
 server_conf=/etc/cs16-server/cs16-server.conf
 
 useradd -m -s /bin/bash $server_user
-passwd -dl $server_user
+passwd -l $server_user
 
 install -vm 755 cs16-server -t /usr/bin
 install -vDm 644 cs16-server.conf "$server_conf"
@@ -85,8 +90,6 @@ fi
 
 printf '\nInstallation completed\n\n'
 
-# Notes
-#
 # Admin access
 # [cs16/cstrike/addons/amxmodx/configs/users.ini]
 # "STEAM_0:0:YOUR_STEAM_ID" "" "abcdefghijklmnopqrstuv" "ce"
