make tty-colorscheme posix compatible

diff --git a/extra/.other/scripts/tty-colorscheme-posix/tty-colorscheme b/extra/.other/scripts/tty-colorscheme-posix/tty-colorscheme
--- a/extra/.other/scripts/tty-colorscheme-posix/tty-colorscheme
+++ b/extra/.other/scripts/tty-colorscheme-posix/tty-colorscheme
@@ -3,12 +3,12 @@
 colorschemes_dir="/etc/tty-colorscheme/colorschemes"
 
 print_help() {
-	echo "Usage: tty-colorscheme [flags | colorscheme]"
-	echo "  -l    list colorschemes"
-	echo "  -c    list colorschemes and print their colors"
-	echo "  -p    print current color palette"
-	echo "  -r    pick a random colorscheme"
-	echo "  -h    print help"
+	printf 'Usage: tty-colorscheme [flags | colorscheme]\n'
+	printf '  -l    list colorschemes\n'
+	printf '  -c    list colorschemes and print their colors\n'
+	printf '  -p    print current color palette\n'
+	printf '  -r    pick a random colorscheme\n'
+	printf '  -h    print help\n'
 }
 
 if [ $# -eq 0 ]; then
@@ -22,7 +22,7 @@ while getopts ":lcprh" opt; do
 		p) PRINT_CURRENT_PALETTE=1;;
 		r) PICK_RANDOM_COLORSCHEME=1;;
 		h) PRINT_HELP=1;;
-		*) echo "Invalid option -$OPTARG" && print_help && exit 1;;
+		*) printf 'Invalid option -%s\n' "$OPTARG" && print_help && exit 1;;
 	esac
 done
 
@@ -31,7 +31,7 @@ shift "$((OPTIND-1))"
 if [ -n "$PRINT_SCHEMES" ] || [ -n "$PRINT_COLORED_SCHEMES" ]; then
 	for scheme_file in "$colorschemes_dir"/*; do
 		scheme_name="$(basename "$scheme_file")"
-		echo "$scheme_name"
+		printf '%s\n' "$scheme_name"
 		if [ -n "$PRINT_COLORED_SCHEMES" ]; then
 			cnt=0
 			while IFS= read -r line || [ -n "$line" ]; do
@@ -44,7 +44,7 @@ if [ -n "$PRINT_SCHEMES" ] || [ -n "$PRINT_COLORED_SCHEMES" ]; then
 				printf '\e[48;2;%d;%d;%dm   \e[0m' 0x"$r" 0x"$g" 0x"$b"
 				cnt=$((cnt+1))
 				if [ $((cnt % 8)) -eq 0 ]; then
-					echo
+					printf '\n'
 				fi
 			done < "$scheme_file"
 		fi
@@ -80,7 +80,7 @@ if [ "$OPTIND" -eq 1 ] && [ -n "$1" ] || [ -n "$PICK_RANDOM_COLORSCHEME" ]; then
 	else
 		colorscheme="$1"
 		if [ ! -f "$colorschemes_dir/$colorscheme" ]; then
-			echo "Invalid colorscheme"
+			printf 'Invalid colorscheme\n'
 			exit 1
 		fi
 	fi
@@ -111,5 +111,5 @@ if [ "$OPTIND" -eq 1 ] && [ -n "$1" ] || [ -n "$PICK_RANDOM_COLORSCHEME" ]; then
 	if [ "$TERM" = "linux" ]; then
 		clear
 	fi
-	echo "Setting $colorscheme colorscheme"
+	printf 'Setting %s colorscheme' "$colorscheme"
 fi
