bootstrap: update

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -37,9 +37,13 @@ case $1 in
         ;;
 esac
 
-pkgs="curl ssh git tar gzip"
+if [ $mode = workstation ] && [ ! -f $HOME/github/id_ed25519 ]
+then
+    printf "missing ssh private key\n" 1>&2
+    exit 1
+fi
 
-[ $mode = workstation ] && pkgs="$pkgs gpg"
+pkgs="git ssh"
 
 for pkg in $pkgs
 do
@@ -54,27 +58,22 @@ fi
 
 cd "$HOME"
 
-mkdir -m 700 .ssh
+mkdir -pm 700 .ssh
+touch .ssh/authorized_keys
+chmod 600 .ssh/authorized_keys
+
 mkdir repos
 mkdir .config
 
 if [ $mode = workstation ]
 then
-    curl -fLO https://github.com/red-magic/dotfiles/raw/master/archive.tar.gz.gpg
-    gpg -do archive.tar.gz archive.tar.gz.gpg
-    tar xzf archive.tar.gz
-    gpg --import archive/gpg/*.*
-    printf "trust\n5\ny\nsave\n" | gpg --command-fd 0 --edit-key DB9A54FFE9854317497D69BB159C66B3104E3E30
-    cp -f archive/ssh/id_ed25519 .ssh
-    cp -f archive/ssh/id_ed25519.pub .ssh
-    cp -f archive/ssh/id_ed25519.pub .ssh/authorized_keys
+    curl -fL https://github.com/red-magic/dotfiles/raw/master/.ssh/config -o .ssh/config
+    cp -f github/id_ed25519 .ssh
+    cp -f github/id_ed25519.pub .ssh
     touch .ssh/known_hosts
     chmod 600 .ssh/known_hosts
-    chmod 600 .ssh/authorized_keys
-    rm -rf archive*
-
-    curl -fL https://github.com/red-magic/dotfiles/raw/master/.ssh/config -o .ssh/config
     chmod 600 .ssh/config
+
     eval "$(ssh-agent -s)"
     ssh-add
     git clone ssh://git@github.com/red-magic/dotfiles repos/dotfiles
