scripts: update

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -2,23 +2,54 @@
 
 set -e
 
-[ $# -ne 1 ] && exit 1
+progname=$(basename "$0")
 
-case $1 in
-    -s) ;;
-    -w) workstation=1 ;;
-    *) exit 1 ;;
-esac
+print_help()
+{
+    printf "usage: %s -s|-w\n" "$progname"
+}
+
+if [ -z "$1" ]
+then
+    print_help
+    exit 0
+fi
+
+while getopts :sw opt
+do
+    case $opt in
+        s)
+            workstation=0
+            ;;
+        w)
+            workstation=1
+            ;;
+        *)
+            printf "%s: invalid option -%s\n" "$progname" "$OPTARG" >&2
+            print_help
+            exit 1
+            ;;
+    esac
+done
+
+if [ "$OPTIND" -ne 2 ]
+then
+    printf "%s: only one option is accepted\n" "$progname" >&2
+    print_help
+    exit 1
+fi
 
 pkgs="curl ssh git tar gzip"
 
-[ -n "$workstation" ] && pkgs="$pkgs gpg"
+[ "$workstation" -eq 1 ] && pkgs="$pkgs gpg"
 
-for pkg in $pkgs; do
+for pkg in $pkgs
+do
     [ -x "$(command -v "$pkg")" ] || missing_pkgs="$missing_pkgs $pkg"
 done
 
-if [ -n "$missing_pkgs" ]; then
+if [ -n "$missing_pkgs" ]
+then
     printf "Install missing packages:%s\n" "$missing_pkgs"
     exit 1
 fi
@@ -29,7 +60,8 @@ mkdir -m 700 .ssh
 mkdir repos
 mkdir .config
 
-if [ -n "$workstation" ]; then
+if [ "$workstation" -eq 1 ]
+then
     curl -LO https://github.com/red-magic/dotfiles/raw/master/archive.tar.gz.gpg
     gpg -do archive.tar.gz archive.tar.gz.gpg
     tar xzf archive.tar.gz
@@ -48,15 +80,18 @@ if [ -n "$workstation" ]; then
     ssh-add
     git clone ssh://git@github.com/red-magic/dotfiles repos/dotfiles
     git clone ssh://git@github.com/red-magic/bible repos/bible
-    if uname -s | grep -q Linux; then
+    if uname -s | grep -q Linux
+    then
         cp -rf repos/dotfiles/.docker .
         git clone ssh://git@github.com/red-magic/tty-colorscheme repos/tty-colorscheme
         git clone ssh://git@github.com/red-magic/cs16-server repos/cs16-server
         git clone ssh://git@github.com/red-magic/arti-bin repos/arti-bin
-        if [ -f /etc/arch-release ]; then
+        if [ -f /etc/arch-release ]
+        then
             aur_pkgs="pacproxy-bin simple-and-soft-cursor snowflake-pt-client-bin tor-relay-scanner-bin ttf-go tty-colorscheme windows-10-cursor"
             mkdir repos/aur
-            for aur_pkg in $aur_pkgs; do
+            for aur_pkg in $aur_pkgs
+            do
                 git clone "ssh://aur@aur.archlinux.org/$aur_pkg" "repos/aur/$aur_pkg"
             done
         fi
@@ -67,20 +102,23 @@ if [ -n "$workstation" ]; then
     cp -f repos/dotfiles/.gitconfig .
 fi
 
-[ -z "$workstation" ] && git clone https://github.com/red-magic/dotfiles repos/dotfiles
+[ "$workstation" -eq 1 ] && git clone https://github.com/red-magic/dotfiles repos/dotfiles
 
 mkdir .config/ranger
 cp -f repos/dotfiles/.config/ranger/rc.conf .config/ranger
 
-if uname -s | grep -q Linux; then
+if uname -s | grep -q Linux
+then
     cp -f repos/dotfiles/.bash_profile .
     cp -f repos/dotfiles/.bashrc .
-elif uname -s | grep -q BSD; then
+elif uname -s | grep -q BSD
+then
     cp -f repos/dotfiles/.profile .
     cp -f repos/dotfiles/.kshrc .
     cp -f repos/dotfiles/.mailrc .
     chmod 700 "$HOME"
-    if [ -n "$workstation" ]; then
+    if [ "$workstation" -eq 1 ]
+    then
         cp -f repos/dotfiles/.cwmrc .
         cp -f repos/dotfiles/.xsession .
         cp -f repos/dotfiles/.Xdefaults .
diff --git a/scripts/crypt-gpg b/scripts/crypt-gpg
--- a/scripts/crypt-gpg
+++ b/scripts/crypt-gpg
@@ -2,68 +2,103 @@
 
 set -e
 
-print_help() {
-    printf "usage: %s enc|enc-asym|dec file\n" "$(basename "$0")"
+progname=$(basename "$0")
+
+print_help()
+{
+    printf "usage: %s enc|enc-asym|dec file\n" "$progname"
 }
 
-if [ $# -gt 2 ]; then
-    printf "%s: too many arguments\n" "$(basename "$0")" >&2
+if [ $# -gt 2 ]
+then
+    printf "%s: too many arguments\n" "$progname" >&2
     print_help
     exit 1
 fi
 
-case $1 in
-    enc | enc-asym | dec)
-        if [ -z "$2" ]; then
-            printf "%s: %s: missing file argument\n" "$(basename "$0")" "$1" >&2
-            print_help
-            exit 1
-        elif [ ! -f "$2" ]; then
-            printf "%s: %s: file %s doesn't exist\n" "$(basename "$0")" "$1" "$2" >&2
-            exit 1
-        fi
-        ;;
+cmd=$1
+file=$2
+
+case $cmd in
+    enc | enc-asym | dec) ;;
     "")
         print_help
         exit 0
         ;;
-
     *)
-        printf "%s: invalid command: %s\n" "$(basename "$0")" "$1" >&2
+        printf "%s: invalid command: %s\n" "$progname" "$cmd" >&2
         exit 1
         ;;
 esac
 
-case $1 in
-    enc)
-        if [ -f "$(basename "$2").gpg" ]; then
-            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").gpg" >&2
+if [ -z "$file" ]
+then
+    printf "%s: %s: missing file argument\n" "$progname" "$cmd" >&2
+    print_help
+    exit 1
+fi
+
+case $cmd in
+    enc | enc-asym)
+        file_dec=$file
+        file_enc=$file.gpg
+
+        if [ ! -f "$file_dec" ]
+        then
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_dec" >&2
             exit 1
         fi
-        gpg -o "$(basename "$2").gpg" \
+
+        if [ -f "$file_enc" ]
+        then
+            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_enc" >&2
+            exit 1
+        fi
+        ;;
+    dec)
+        case $file in
+            *.gpg) ;;
+            *)
+                printf "%s: %s: not a .gpg file: %s\n" "$progname" "$cmd" "$file" >&2
+                exit 1
+                ;;
+        esac
+
+        file_enc=$file
+        file_dec=${file%.gpg}
+
+        if [ ! -f "$file_enc" ]
+        then
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_enc" >&2
+            exit 1
+        fi
+
+        if [ -f "$file_dec" ]
+        then
+            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_dec" >&2
+            exit 1
+        fi
+        ;;
+esac
+
+case $cmd in
+    enc)
+        gpg -o "$file_enc" \
             --s2k-cipher-algo AES256 \
             --s2k-digest-algo SHA512 \
             --force-aead \
             --no-compress \
-            -c "$2"
+            -c "$file_dec"
         ;;
     enc-asym)
-        if [ -f "$(basename "$2").gpg" ]; then
-            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").gpg" >&2
-            exit 1
-        fi
-        gpg -o "$(basename "$2").gpg" \
+        gpg -o "$file_enc" \
             --cipher-algo AES256 \
             --digest-algo SHA512 \
             --force-aead \
             --no-compress \
-            -es "$2"
+            -es "$file_dec"
         ;;
     dec)
-        if [ -f "$(basename "$2" .gpg)" ]; then
-            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2" .gpg)" >&2
-            exit 1
-        fi
-        gpg -do "$(basename "$2" .gpg)" "$2"
+        gpg -do "$file_dec" "$file_enc"
         ;;
 esac
diff --git a/scripts/crypt-openssl b/scripts/crypt-openssl
--- a/scripts/crypt-openssl
+++ b/scripts/crypt-openssl
@@ -2,44 +2,87 @@
 
 set -e
 
-print_help() {
-    printf "usage: %s enc|dec file\n" "$(basename "$0")"
+progname=$(basename "$0")
+
+print_help()
+{
+    printf "usage: %s enc|dec file\n" "$progname"
 }
 
-if [ $# -gt 2 ]; then
-    printf "%s: too many arguments\n" "$(basename "$0")" >&2
+if [ $# -gt 2 ]
+then
+    printf "%s: too many arguments\n" "$progname" >&2
     print_help
     exit 1
 fi
 
-case $1 in
-    enc | dec)
-        if [ -z "$2" ]; then
-            printf "%s: %s: missing file argument\n" "$(basename "$0")" "$1" >&2
-            print_help
-            exit 1
-        elif [ ! -f "$2" ]; then
-            printf "%s: %s: file %s doesn't exist\n" "$(basename "$0")" "$1" "$2" >&2
-            exit 1
-        fi
-        ;;
+cmd=$1
+file=$2
+
+case $cmd in
+    enc | dec) ;;
     "")
         print_help
         exit 0
         ;;
-
     *)
-        printf "%s: invalid command: %s\n" "$(basename "$0")" "$1" >&2
+        printf "%s: invalid command: %s\n" "$progname" "$cmd" >&2
         exit 1
         ;;
 esac
 
-case $1 in
+if [ -z "$file" ]
+then
+    printf "%s: %s: missing file argument\n" "$progname" "$cmd" >&2
+    print_help
+    exit 1
+fi
+
+case $cmd in
     enc)
-        if [ -f "$(basename "$2").enc" ]; then
-            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").enc" >&2
+        file_dec=$file
+        file_enc=$file.enc
+
+        if [ ! -f "$file_dec" ]
+        then
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_dec" >&2
             exit 1
         fi
+
+        if [ -f "$file_enc" ]
+        then
+            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_enc" >&2
+            exit 1
+        fi
+        ;;
+    dec)
+        case $file in
+            *.enc) ;;
+            *)
+                printf "%s: %s: not a .enc file: %s\n" "$progname" "$cmd" "$file" >&2
+                exit 1
+                ;;
+        esac
+
+        file_enc=$file
+        file_dec=${file%.enc}
+
+        if [ ! -f "$file_enc" ]
+        then
+            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_enc" >&2
+            exit 1
+        fi
+
+        if [ -f "$file_dec" ]
+        then
+            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_dec" >&2
+            exit 1
+        fi
+        ;;
+esac
+
+case $cmd in
+    enc)
         openssl enc \
                 -e \
                 -aes-256-cbc \
@@ -47,14 +90,10 @@ case $1 in
                 -pbkdf2 \
                 -iter 1000000 \
                 -salt \
-                -in "$2" \
-                -out "$(basename "$2").enc"
+                -in "$file_dec" \
+                -out "$file_enc"
         ;;
     dec)
-        if [ -f "$(basename "$2" .enc)" ]; then
-            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2" .enc)" >&2
-            exit 1
-        fi
         openssl enc \
                 -d \
                 -aes-256-cbc \
@@ -62,7 +101,7 @@ case $1 in
                 -pbkdf2 \
                 -iter 1000000 \
                 -salt \
-                -in "$2" \
-                -out "$(basename "$2" .enc)"
+                -in "$file_enc" \
+                -out "$file_dec"
         ;;
 esac
diff --git a/scripts/qemu-launch-vm b/scripts/qemu-launch-vm
--- a/scripts/qemu-launch-vm
+++ b/scripts/qemu-launch-vm
@@ -7,18 +7,30 @@ qemu_args="-cpu host -smp 16 -m 8G -net nic -net user,hostfwd=tcp::2222-:22 -aud
 cd_args=
 drive_args=
 
-while getopts :d:c: opt; do
+while getopts :d:c: opt
+do
     # -enable-kvm Linux
     # -enable-vvm OpenBSD
     case $opt in
-        c) cd_args="-cdrom '$OPTARG'" ;;
-        d) drive_args="-drive 'file=$OPTARG,format=raw'" ;;
-        :) printf "Option -%s requires an argument\n" "$OPTARG" && exit 1 ;;
-        *) printf "Invalid option -%s\n" "$OPTARG" && exit 1 ;;
+        c)
+            cd_args="-cdrom '$OPTARG'"
+            ;;
+        d)
+            drive_args="-drive 'file=$OPTARG,format=raw'"
+            ;;
+        :)
+            printf "Option -%s requires an argument\n" "$OPTARG" >&2
+            exit 1
+            ;;
+        *)
+            printf "Invalid option -%s\n" "$OPTARG" >&2
+            exit 1
+            ;;
     esac
 done
 
-if [ -z "$drive_args" ] && [ -z "$cd_args" ]; then
+if [ -z "$drive_args" ] && [ -z "$cd_args" ]
+then
     printf "Usage: %s -d <system.img> -c <cd.iso>\n" "$(basename "$0")"
     exit 1
 fi
