scripts: update

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -11,12 +11,10 @@ print_help()
 
 if [ $# -gt 1 ]
 then
-    printf "%s: only one option is accepted\n" "$progname" >&2
+    printf "%s: only 1 option is accepted\n" "$progname" >&2
     print_help
     exit 1
-fi
-
-if [ -z "$1" ]
+elif [ -z "$1" ]
 then
     print_help
     exit 0
@@ -30,7 +28,7 @@ case $1 in
         workstation=1
         ;;
     *)
-        printf "%s: invalid option -%s\n" "$progname" "$1" >&2
+        printf "%s: invalid option %s\n" "$progname" "$1" >&2
         print_help
         exit 1
         ;;
