scripts: convert to /bin/sh

diff --git a/scripts/rename-files-to-random-name b/scripts/rename-files-to-random-name
--- a/scripts/rename-files-to-random-name
+++ b/scripts/rename-files-to-random-name
@@ -7,6 +7,21 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
+os_name=$(uname -s)
+
+case $os_name in
+    *BSD)
+        sha_cmd=sha256
+        ;;
+    Linux)
+        sha_cmd=sha256sum
+        ;;
+    *)
+        printf "Unable to detect OS for \$sha_cmd\n"
+        exit 1
+        ;;
+esac
+
 target_dir=$1
 
 cd "$target_dir"
@@ -15,7 +30,7 @@ for file in *; do
     if [ -f "$file" ]; then
         extension=${file##*.}
         if [ "$extension" != "$file" ]; then
-            newname=$(dd if=/dev/urandom bs=256 count=1 2> /dev/null | sha256 | cut -c 1-32)
+            newname=$(dd if=/dev/urandom bs=256 count=1 2> /dev/null | $sha_cmd | cut -c 1-32)
             mv -vf -- "$file" "$newname"."$extension"
         fi
     fi
